name: Dependency Updates

on:
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Monday at 6 AM UTC
  workflow_dispatch:

env:
  NIX_CONFIG: |
    experimental-features = nix-command flakes
    accept-flake-config = true

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: "${{ github.workspace }}/scripts/nix-env.sh {0}"
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: ./.github/actions/setup-nix
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Check current dependency status
      run: just check-dependency-freshness

    - name: Update Nix flake inputs
      run: |
        echo "Current flake.lock:"
        git log -1 --format="%h %cd %s" --date=short flake.lock || echo "No previous commits for flake.lock"
        
        nix flake update
        
        echo "Updated flake.lock:"
        git diff --stat flake.lock || echo "No changes to flake.lock"

    - name: Update dependencies and test
      run: just update-dependencies

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@0f2a09222f84e1d0d078fdec150cbe3ff4c5b799 # v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: Weekly dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated updates to project dependencies:
          
          ### Changes Made:
          - Updated Nix flake inputs (`flake.lock`)
          - Updated Rust crate dependencies in all `Cargo.lock` files
          
          ### Testing:
          - ✅ Code quality checks passed
          - ✅ Build matrix completed successfully
          
          ### Review Notes:
          - Please review the dependency changes for any breaking changes
          - CI pipeline will run full tests on this PR
          - Consider testing locally with `just ci-full` before merging
          
          **Auto-generated by dependency-updates workflow**
        branch: automated/dependency-updates
        delete-branch: true
        labels: |
          dependencies
          automated